window.LOCAL_NSE_STOCKS = [
  { "symbol": "RELIANCE", "name": "Reliance Industries Ltd.", "industry": "Energy" },
  { "symbol": "TCS", "name": "Tata Consultancy Services Ltd.", "industry": "Information Technology" },
  { "symbol": "HDFCBANK", "name": "HDFC Bank Ltd.", "industry": "Financial Services" },
  { "symbol": "INFY", "name": "Infosys Ltd.", "industry": "Information Technology" },
  { "symbol": "ICICIBANK", "name": "ICICI Bank Ltd.", "industry": "Financial Services" },
  { "symbol": "HINDUNILVR", "name": "Hindustan Unilever Ltd.", "industry": "Consumer Goods" },
  { "symbol": "ITC", "name": "ITC Ltd.", "industry": "Consumer Goods" },
  { "symbol": "SBIN", "name": "State Bank of India", "industry": "Financial Services" },
  { "symbol": "BHARTIARTL", "name": "Bharti Airtel Ltd.", "industry": "Telecommunications" },
  { "symbol": "KOTAKBANK", "name": "Kotak Mahindra Bank Ltd.", "industry": "Financial Services" },
  { "symbol": "LT", "name": "Larsen & Toubro Ltd.", "industry": "Construction" },
  { "symbol": "AXISBANK", "name": "Axis Bank Ltd.", "industry": "Financial Services" },
  { "symbol": "ASIANPAINT", "name": "Asian Paints Ltd.", "industry": "Consumer Goods" },
  { "symbol": "MARUTI", "name": "Maruti Suzuki India Ltd.", "industry": "Automobile" },
  { "symbol": "HCLTECH", "name": "HCL Technologies Ltd.", "industry": "Information Technology" },
  { "symbol": "SUNPHARMA", "name": "Sun Pharmaceutical Industries Ltd.", "industry": "Healthcare" },
  { "symbol": "BAJFINANCE", "name": "Bajaj Finance Ltd.", "industry": "Financial Services" },
  { "symbol": "WIPRO", "name": "Wipro Ltd.", "industry": "Information Technology" },
  { "symbol": "ULTRACEMCO", "name": "UltraTech Cement Ltd.", "industry": "Materials" },
  { "symbol": "TITAN", "name": "Titan Company Ltd.", "industry": "Consumer Goods" },
  { "symbol": "NESTLEIND", "name": "Nestle India Ltd.", "industry": "Consumer Goods" },
  { "symbol": "JSWSTEEL", "name": "JSW Steel Ltd.", "industry": "Materials" },
  { "symbol": "GRASIM", "name": "Grasim Industries Ltd.", "industry": "Materials" },
  { "symbol": "POWERGRID", "name": "Power Grid Corporation of India Ltd.", "industry": "Utilities" },
  { "symbol": "NTPC", "name": "NTPC Ltd.", "industry": "Utilities" },
  { "symbol": "ADANIENT", "name": "Adani Enterprises Ltd.", "industry": "Metals & Mining" },
  { "symbol": "ADANIPORTS", "name": "Adani Ports and Special Economic Zone Ltd.", "industry": "Services" },
  { "symbol": "ONGC", "name": "Oil & Natural Gas Corporation Ltd.", "industry": "Energy" },
  { "symbol": "COALINDIA", "name": "Coal India Ltd.", "industry": "Energy" },
  { "symbol": "TATASTEEL", "name": "Tata Steel Ltd.", "industry": "Materials" },
  { "symbol": "TATAMOTORS", "name": "Tata Motors Ltd.", "industry": "Automobile" },
  { "symbol": "M&M", "name": "Mahindra & Mahindra Ltd.", "industry": "Automobile" },
  { "symbol": "HDFCLIFE", "name": "HDFC Life Insurance Company Ltd.", "industry": "Financial Services" },
  { "symbol": "SBILIFE", "name": "SBI Life Insurance Company Ltd.", "industry": "Financial Services" },
  { "symbol": "INDUSINDBK", "name": "IndusInd Bank Ltd.", "industry": "Financial Services" },
  { "symbol": "BPCL", "name": "Bharat Petroleum Corporation Ltd.", "industry": "Energy" },
  { "symbol": "HINDALCO", "name": "Hindalco Industries Ltd.", "industry": "Materials" },
  { "symbol": "APOLLOHOSP", "name": "Apollo Hospitals Enterprise Ltd.", "industry": "Healthcare" },
  { "symbol": "EICHERMOT", "name": "Eicher Motors Ltd.", "industry": "Automobile" },
  { "symbol": "DIVISLAB", "name": "Divi's Laboratories Ltd.", "industry": "Healthcare" },
  { "symbol": "BAJAJ-AUTO", "name": "Bajaj Auto Ltd.", "industry": "Automobile" },
  { "symbol": "CIPLA", "name": "Cipla Ltd.", "industry": "Healthcare" },
  { "symbol": "TECHM", "name": "Tech Mahindra Ltd.", "industry": "Information Technology" },
  { "symbol": "TATACONSUM", "name": "Tata Consumer Products Ltd.", "industry": "Consumer Goods" },
  { "symbol": "HEROMOTOCO", "name": "Hero MotoCorp Ltd.", "industry": "Automobile" },
  { "symbol": "BRITANNIA", "name": "Britannia Industries Ltd.", "industry": "Consumer Goods" },
  { "symbol": "SHRIRAMFIN", "name": "Shriram Finance Ltd.", "industry": "Financial Services" },
  { "symbol": "DRREDDY", "name": "Dr. Reddy's Laboratories Ltd.", "industry": "Healthcare" },
  { "symbol": "GRSE", "name": "Garden Reach Shipbuilders & Engineers Ltd.", "industry": "Industrials" },
  { "symbol": "IREDA", "name": "Indian Renewable Energy Development Agency Ltd.", "industry": "Financial Services" },
  { "symbol": "IRFC", "name": "Indian Railway Finance Corporation Ltd.", "industry": "Financial Services" },
  { "symbol": "RVNL", "name": "Rail Vikas Nigam Ltd.", "industry": "Construction" },
  { "symbol": "RELAXO", "name": "Relaxo Footwears Ltd.", "industry": "Consumer Goods" },
  { "symbol": "SPARC", "name": "Sun Pharma Advanced Research Company Ltd.", "industry": "Healthcare" },
  { "symbol": "SUZLON", "name": "Suzlon Energy Ltd.", "industry": "Utilities" },
  { "symbol": "NHPC", "name": "NHPC Ltd.", "industry": "Utilities" },
  { "symbol": "ZOMATO", "name": "Zomato Ltd.", "industry": "Consumer Services" },
  { "symbol": "NYKAA", "name": "FSN E-Commerce Ventures Ltd. (Nykaa)", "industry": "Consumer Services" },
  { "symbol": "PAYTM", "name": "One 97 Communications Ltd. (Paytm)", "industry": "Financial Services" },
  { "symbol": "JIOFIN", "name": "Jio Financial Services Ltd.", "industry": "Financial Services" },
  { "symbol": "TRENT", "name": "Trent Ltd.", "industry": "Consumer Services" },
  { "symbol": "HAL", "name": "Hindustan Aeronautics Ltd.", "industry": "Industrials" },
  { "symbol": "BEL", "name": "Bharat Electronics Ltd.", "industry": "Industrials" },
  { "symbol": "BHEL", "name": "Bharat Heavy Electricals Ltd.", "industry": "Industrials" },
  { "symbol": "SAIL", "name": "Steel Authority of India Ltd.", "industry": "Materials" },
  { "symbol": "GMRINFRA", "name": "GMR Airports Infrastructure Ltd.", "industry": "Services" },
  { "symbol": "TATACOMM", "name": "Tata Communications Ltd.", "industry": "Telecommunications" },
  { "symbol": "TATAPOWER", "name": "Tata Power Company Ltd.", "industry": "Utilities" },
  { "symbol": "VBL", "name": "Varun Beverages Ltd.", "industry": "Consumer Goods" },
  { "symbol": "DLF", "name": "DLF Ltd.", "industry": "Construction" },
  { "symbol": "LICI", "name": "Life Insurance Corporation of India", "industry": "Financial Services" },
  { "symbol": "INDIGO", "name": "InterGlobe Aviation Ltd. (IndiGo)", "industry": "Services" },
  { "symbol": "PIDILITIND", "name": "Pidilite Industries Ltd.", "industry": "Chemicals" },
  { "symbol": "SIEMENS", "name": "Siemens Ltd.", "industry": "Industrials" },
  { "symbol": "ABB", "name": "ABB India Ltd.", "industry": "Industrials" },
  { "symbol": "HAVELLS", "name": "Havells India Ltd.", "industry": "Consumer Goods" },
  { "symbol": "SRF", "name": "SRF Ltd.", "industry": "Chemicals" },
  { "symbol": "MARICO", "name": "Marico Ltd.", "industry": "Consumer Goods" },
  { "symbol": "GODREJCP", "name": "Godrej Consumer Products Ltd.", "industry": "Consumer Goods" },
  { "symbol": "DABUR", "name": "Dabur India Ltd.", "industry": "Consumer Goods" },
  { "symbol": "COLPAL", "name": "Colgate-Palmolive (India) Ltd.", "industry": "Consumer Goods" },
  { "symbol": "BERGEPAINT", "name": "Berger Paints India Ltd.", "industry": "Consumer Goods" },
  { "symbol": "SHREECEM", "name": "Shree Cement Ltd.", "industry": "Materials" },
  { "symbol": "AMBUJACEM", "name": "Ambuja Cements Ltd.", "industry": "Materials" },
  { "symbol": "ACC", "name": "ACC Ltd.", "industry": "Materials" },
  { "symbol": "JINDALSTEL", "name": "Jindal Steel & Power Ltd.", "industry": "Materials" },
  { "symbol": "NMDC", "name": "NMDC Ltd.", "industry": "Metals & Mining" },
  { "symbol": "CONCOR", "name": "Container Corporation of India Ltd.", "industry": "Services" },
  { "symbol": "GAIL", "name": "GAIL (India) Ltd.", "industry": "Energy" },
  { "symbol": "IOC", "name": "Indian Oil Corporation Ltd.", "industry": "Energy" },
  { "symbol": "MRF", "name": "MRF Ltd.", "industry": "Automobile" },
  { "symbol": "BALKRISIND", "name": "Balkrishna Industries Ltd.", "industry": "Automobile" },
  { "symbol": "MUTHOOTFIN", "name": "Muthoot Finance Ltd.", "industry": "Financial Services" },
  { "symbol": "CHOLAFIN", "name": "Cholamandalam Investment and Finance Company Ltd.", "industry": "Financial Services" },
  { "symbol": "BANDHANBNK", "name": "Bandhan Bank Ltd.", "industry": "Financial Services" },
  { "symbol": "IDFCFIRSTB", "name": "IDFC First Bank Ltd.", "industry": "Financial Services" },
  { "symbol": "AUBANK", "name": "AU Small Finance Bank Ltd.", "industry": "Financial Services" },
  { "symbol": "YESBANK", "name": "Yes Bank Ltd.", "industry": "Financial Services" },
  { "symbol": "PNB", "name": "Punjab National Bank", "industry": "Financial Services" },
  { "symbol": "BANKBARODA", "name": "Bank of Baroda", "industry": "Financial Services" },
  { "symbol": "CANBK", "name": "Canara Bank", "industry": "Financial Services" },
  { "symbol": "UNIONBANK", "name": "Union Bank of India", "industry": "Financial Services" },
  { "symbol": "IOB", "name": "Indian Overseas Bank", "industry": "Financial Services" },
  { "symbol": "UCOBANK", "name": "UCO Bank", "industry": "Financial Services" },
  { "symbol": "CENTRALBK", "name": "Central Bank of India", "industry": "Financial Services" },
  { "symbol": "MAHABANK", "name": "Bank of Maharashtra", "industry": "Financial Services" },
  { "symbol": "BOI", "name": "Bank of India", "industry": "Financial Services" },
  { "symbol": "INDIANB", "name": "Indian Bank", "industry": "Financial Services" },
  { "symbol": "UBL", "name": "United Breweries Ltd.", "industry": "Consumer Goods" },
  { "symbol": "MCDOWELL-N", "name": "United Spirits Ltd. (McDowell's)", "industry": "Consumer Goods" },
  { "symbol": "LUPIN", "name": "Lupin Ltd.", "industry": "Healthcare" },
  { "symbol": "AUROPHARMA", "name": "Aurobindo Pharma Ltd.", "industry": "Healthcare" },
  { "symbol": "BIOCON", "name": "Biocon Ltd.", "industry": "Healthcare" },
  { "symbol": "GLAND", "name": "Gland Pharma Ltd.", "industry": "Healthcare" },
  { "symbol": "TORNTPHARM", "name": "Torrent Pharmaceuticals Ltd.", "industry": "Healthcare" },
  { "symbol": "ALKEM", "name": "Alkem Laboratories Ltd.", "industry": "Healthcare" },
  { "symbol": "IPCALAB", "name": "Ipca Laboratories Ltd.", "industry": "Healthcare" },
  { "symbol": "SYNGENE", "name": "Syngene International Ltd.", "industry": "Healthcare" },
  { "symbol": "VOLTAS", "name": "Voltas Ltd.", "industry": "Consumer Durables" },
  { "symbol": "BLUESTARCO", "name": "Blue Star Ltd.", "industry": "Consumer Durables" },
  { "symbol": "DIXON", "name": "Dixon Technologies (India) Ltd.", "industry": "Consumer Durables" },
  { "symbol": "POLYCAB", "name": "Polycab India Ltd.", "industry": "Industrials" },
  { "symbol": "KEI", "name": "KEI Industries Ltd.", "industry": "Industrials" },
  { "symbol": "PERSISTENT", "name": "Persistent Systems Ltd.", "industry": "Information Technology" },
  { "symbol": "COFORGE", "name": "Coforge Ltd.", "industry": "Information Technology" },
  { "symbol": "MPHASIS", "name": "Mphasis Ltd.", "industry": "Information Technology" },
  { "symbol": "LTTS", "name": "L&T Technology Services Ltd.", "industry": "Information Technology" },
  { "symbol": "KPITTECH", "name": "KPIT Technologies Ltd.", "industry": "Information Technology" },
  { "symbol": "TATAELXSI", "name": "Tata Elxsi Ltd.", "industry": "Information Technology" },
  { "symbol": "CYIENT", "name": "Cyient Ltd.", "industry": "Information Technology" },
  { "symbol": "SONACOMS", "name": "Sona BLW Precision Forgings Ltd.", "industry": "Automobile" },
  { "symbol": "ENDURANCE", "name": "Endurance Technologies Ltd.", "industry": "Automobile" },
  { "symbol": "DEEPAKNTR", "name": "Deepak Nitrite Ltd.", "industry": "Chemicals" },
  { "symbol": "TATACHEM", "name": "Tata Chemicals Ltd.", "industry": "Chemicals" },
  { "symbol": "AARTIIND", "name": "Aarti Industries Ltd.", "industry": "Chemicals" },
  { "symbol": "ATGL", "name": "Adani Total Gas Ltd.", "industry": "Utilities" },
  { "symbol": "AWL", "name": "Adani Wilmar Ltd.", "industry": "Consumer Goods" },
  { "symbol": "ADANIGREEN", "name": "Adani Green Energy Ltd.", "industry": "Utilities" },
  { "symbol": "ADANIPOWER", "name": "Adani Power Ltd.", "industry": "Utilities" },
  { "symbol": "ADANITRANS", "name": "Adani Energy Solutions Ltd.", "industry": "Utilities" },
  { "symbol": "CGPOWER", "name": "CG Power and Industrial Solutions Ltd.", "industry": "Industrials" },
  { "symbol": "TATAINVEST", "name": "Tata Investment Corporation Ltd.", "industry": "Financial Services" },
  { "symbol": "FACT", "name": "Fertilisers and Chemicals Travancore Ltd.", "industry": "Chemicals" },
  { "symbol": "HUDCO", "name": "Housing & Urban Development Corporation Ltd.", "industry": "Financial Services" },
  { "symbol": "RPOWER", "name": "Reliance Power Ltd.", "industry": "Utilities" },
  { "symbol": "RELINFRA", "name": "Reliance Infrastructure Ltd.", "industry": "Construction" },
  { "symbol": "RVNL", "name": "Rail Vikas Nigam Ltd.", "industry": "Construction" },
  { "symbol": "NETWEB", "name": "Netweb Technologies India Ltd.", "industry": "Information Technology" }
];
